#!/usr/bin/env python3
import json
from pathlib import Path

# 音标数据 - 自然地理章节前50个单词的音标
phonetics_data = {
    "atmosphere": "/ˈætməsfɪə(r)/",
    "hydrosphere": "/ˈhaɪdrəsfɪə(r)/",
    "lithosphere": "/ˈlɪθəsfɪə(r)/",
    "oxygen": "/ˈɒksɪdʒən/",
    "oxide": "/ˈɒksaɪd/",
    "carbon dioxide": "/ˌkɑːbən daɪˈɒksaɪd/",
    "hydrogen": "/ˈhaɪdrədʒən/",
    "core": "/kɔː(r)/",
    "crust": "/krʌst/",
    "mantle": "/ˈmæntl/",
    "longitude": "/ˈlɒŋɡɪtjuːd/",
    "latitude": "/ˈlætɪtjuːd/",
    "horizon": "/həˈraɪzn/",
    "altitude": "/ˈæltɪtjuːd/",
    "disaster": "/dɪˈzɑːstə(r)/",
    "mishap": "/ˈmɪshæp/",
    "catastrophic": "/ˌkætəˈstrɒfɪk/",
    "calamity": "/kəˈlæməti/",
    "endanger": "/ɪnˈdeɪndʒə(r)/",
    "jeopardise": "/ˈdʒepədaɪz/",
    "jeopardize": "/ˈdʒepərdaɪz/",
    "destructive": "/dɪˈstrʌktɪv/",
    "El Nino": "/el ˈniːnjəʊ/",
    "greenhouse": "/ˈɡriːnhaʊs/",
    "phenomenon": "/fəˈnɒmɪnən/",
    "pebble": "/ˈpebl/",
    "magnet": "/ˈmæɡnət/",
    "ore": "/ɔː(r)/",
    "mineral": "/ˈmɪnərəl/",
    "marble": "/ˈmɑːbl/",
    "quartz": "/kwɔːts/",
    "granite": "/ˈɡrænɪt/",
    "gust": "/ɡʌst/",
    "breeze": "/briːz/",
    "monsoon": "/ˌmɒnˈsuːn/",
    "gale": "/ɡeɪl/",
    "hurricane": "/ˈhʌrɪkən/",
    "tornado": "/tɔːˈneɪdəʊ/",
    "typhoon": "/taɪˈfuːn/",
    "volcano": "/vɒlˈkeɪnəʊ/",
    "erupt": "/ɪˈrʌpt/",
    "magma": "/ˈmæɡmə/",
    "thermodynamic": "/ˌθɜːməʊdaɪˈnæmɪk/",
    "smog": "/smɒɡ/",
    "fume": "/fjuːm/",
    "mist": "/mɪst/",
    "tsunami": "/tsuˈnɑːmi/",
    "drought": "/draʊt/",
    "flooding": "/ˈflʌdɪŋ/",
    "torrent": "/ˈtɒrənt/",
    "earthquake": "/ˈɜːθkweɪk/",
    "seismic": "/ˈsaɪzmɪk/",
    "avalanche": "/ˈævəlɑːnʃ/",
    "terrain": "/təˈreɪn/",
    "landscape": "/ˈlændskeɪp/",
    "continent": "/ˈkɒntɪnənt/",
    "cave": "/keɪv/",
    "cliff": "/klɪf/",
    "glacier": "/ˈɡlæsiə(r)/",
    "swamp": "/swɒmp/",
    "delta": "/ˈdeltə/",
    "plain": "/pleɪn/",
    "plateau": "/ˈplætəʊ/",
    "oasis": "/əʊˈeɪsɪs/",
    "globe": "/ɡləʊb/",
    "hemisphere": "/ˈhemɪsfɪə(r)/",
    "equator": "/ɪˈkweɪtə(r)/",
    "arctic": "/ˈɑːktɪk/",
    "Antarctic": "/ænˈtɑːktɪk/",
    "pole": "/pəʊl/",
    "polar": "/ˈpəʊlə(r)/",
    "axis": "/ˈæksɪs/",
    "deteriorate": "/dɪˈtɪəriəreɪt/",
    "aggravate": "/ˈæɡrəveɪt/",
    "degrade": "/dɪˈɡreɪd/",
    "upgrade": "/ˌʌpˈɡreɪd/",
    "erode": "/ɪˈrəʊd/",
    "Mediterranean": "/ˌmedɪtəˈreɪniən/",
    "Atlantic": "/ətˈlæntɪk/",
    "pacific": "/pəˈsɪfɪk/",
    "ocean": "/ˈəʊʃn/",
    "marine": "/məˈriːn/",
    "navigation": "/ˌnævɪˈɡeɪʃn/",
    "gulf": "/ɡʌlf/",
    "beach": "/biːtʃ/",
    "coast": "/kəʊst/",
    "shore": "/ʃɔː(r)/",
    "tide": "/taɪd/",
    "current": "/ˈkʌrənt/",
    "brook": "/brʊk/",
    "stream": "/striːm/",
    "source": "/sɔːs/",
    "shallow": "/ˈʃæləʊ/",
    "superficial": "/ˌsuːpəˈfɪʃl/",
    "flat": "/flæt/",
    "smooth": "/smuːð/",
    "rough": "/rʌf/",
    "sandy": "/ˈsændi/",
    "stony": "/ˈstəʊni/",
    "vertical": "/ˈvɜːtɪkl/",
    "steep": "/stiːp/",
    "parallel": "/ˈpærəlel/",
    "narrow": "/ˈnærəʊ/",
    "Oceania": "/ˌəʊʃiˈɑːniə/",
    "mainland": "/ˈmeɪnlənd/",
    "peninsula": "/pəˈnɪnsjələ/",
    "climate": "/ˈklaɪmət/",
    "weather": "/ˈweðə(r)/",
    "meteorology": "/ˌmiːtiəˈrɒlədʒi/",
    "mild": "/maɪld/",
    "heating": "/ˈhiːtɪŋ/",
    "moderate": "/ˈmɒdərət/",
    "warm": "/wɔːm/",
    "thermal": "/ˈθɜːml/",
    "tropics": "/ˈtrɒpɪks/",
    "arid": "/ˈærɪd/",
    "moist": "/mɔɪst/",
    "damp": "/dæmp/",
    "humid": "/ˈhjuːmɪd/",
    "snowy": "/ˈsnəʊi/",
    "frost": "/frɒst/",
    "hail": "/heɪl/",
    "thaw": "/θɔː/",
    "chill": "/tʃɪl/",
    "freeze": "/friːz/",
    "frigid": "/ˈfrɪdʒɪd/",
    "tremble": "/ˈtrembl/",
    "shiver": "/ˈʃɪvə(r)/",
    "thunder": "/ˈθʌndə(r)/",
    "lightning": "/ˈlaɪtnɪŋ/",
    "stormy": "/ˈstɔːmi/",
    "downpour": "/ˈdaʊnpɔː(r)/",
    "rainfall": "/ˈreɪnfɔːl/",
    "sprinkle": "/ˈsprɪŋkl/",
    "rainbow": "/ˈreɪnbəʊ/",
    "shower": "/ˈʃaʊə(r)/",
    "Celsius": "/ˈselsiəs/",
    "temperature": "/ˈtemprətʃə(r)/",
    "forecast": "/ˈfɔːkɑːst/",
    "peak": "/piːk/",
    "mount": "/maʊnt/",
    "mountain": "/ˈmaʊntən/",
    "range": "/reɪndʒ/",
    "ridge": "/rɪdʒ/",
    "slope": "/sləʊp/",
    "valley": "/ˈvæli/",
    "hillside": "/ˈhɪlsaɪd/",
    "overlook": "/ˌəʊvəˈlʊk/",
    "southern": "/ˈsʌðən/",
    "oriental": "/ˌɔːriˈentl/",
    "inevitable": "/ɪnˈevɪtəbl/",
    "irreversible": "/ˌɪrɪˈvɜːsəbl/",
    "irregularly": "/ɪˈreɡjələli/",
    "inappropriate": "/ˌɪnəˈprəʊpriət/",
    "abnormal": "/æbˈnɔːml/",
    "sediment": "/ˈsedɪmənt/",
    "silt": "/sɪlt/",
    "muddy": "/ˈmʌdi/",
    "clay": "/kleɪ/",
    "dirt": "/dɜːt/",
    "rural": "/ˈrʊərəl/",
    "suburb": "/ˈsʌbɜːb/",
    "outskirts": "/ˈaʊtskɜːts/",
    "remote": "/rɪˈməʊt/",
    "desolate": "/ˈdesələt/",
    "distant": "/ˈdɪstənt/",
    "adjacent": "/əˈdʒeɪsnt/",
    "toxic": "/ˈtɒksɪk/",
    "pollutant": "/pəˈluːtənt/",
    "contaminate": "/kənˈtæmɪneɪt/",
    "geology": "/dʒiˈɒlədʒi/",
    "border": "/ˈbɔːdə(r)/",
    "margin": "/ˈmɑːdʒɪn/",
    "fringe": "/frɪndʒ/",
    "plate": "/pleɪt/",
    "debris": "/ˈdebriː/",
    "crack": "/kræk/",
    "gap": "/ɡæp/",
    "splendid": "/ˈsplendɪd/",
    "grand": "/ɡrænd/",
    "magnificent": "/mæɡˈnɪfɪsnt/",
    "dramatic": "/drəˈmætɪk/",
    "wilderness": "/ˈwɪldənəs/",
    "desert": "/ˈdezət/",
    "deforest": "/ˌdiːˈfɒrɪst/",
    "barren": "/ˈbærən/",
    "fertile": "/ˈfɜːtaɪl/",
    "fertilise": "/ˈfɜːtəlaɪz/",
    "fertilize": "/ˈfɜːrtəlaɪz/",
    "solar": "/ˈsəʊlə(r)/",
    "lunar": "/ˈluːnə(r)/",
    "calendar": "/ˈkælɪndə(r)/",
    "sunrise": "/ˈsʌnraɪz/",
    "eclipse": "/ɪˈklɪps/",
    "dusk": "/dʌsk/",
    "heaven": "/ˈhevn/",
    "paradise": "/ˈpærədaɪs/",
    "sunshine": "/ˈsʌnʃaɪn/",
    "shade": "/ʃeɪd/",
    "shadow": "/ˈʃædəʊ/",
    "vapour": "/ˈveɪpə(r)/",
    "vapor": "/ˈveɪpər/",
    "evaporate": "/ɪˈvæpəreɪt/",
    "circulate": "/ˈsɜːkjəleɪt/",
    "precipitate": "/prɪˈsɪpɪteɪt/",
    "reservoir": "/ˈrezəvwɑː(r)/",
    "fountain": "/ˈfaʊntən/",
    "spring": "/sprɪŋ/",
    "dew": "/djuː/",
    "pour": "/pɔː(r)/",
    "drain": "/dreɪn/",
    "drip": "/drɪp/",
    "drown": "/draʊn/",
    "blow": "/bləʊ/",
    "puff": "/pʌf/",
    "gush": "/ɡʌʃ/",
    "dense": "/dens/",
    "intensity": "/ɪnˈtensəti/",
    "intensive": "/ɪnˈtensɪv/",
    "emerge": "/ɪˈmɜːdʒ/",
    "flash": "/flæʃ/",
    "float": "/fləʊt/",
    "surrounding": "/səˈraʊndɪŋ/",
    "condition": "/kənˈdɪʃn/",
    "artificial": "/ˌɑːtɪˈfɪʃl/",
    "synthetic": "/sɪnˈθetɪk/",
    "petrol": "/ˈpetrəl/",
    "gas": "/ɡæs/",
    "gasoline": "/ˈɡæsəliːn/",
    "petroleum": "/pəˈtrəʊliəm/"
}

def add_phonetics_to_json():
    """为自然地理章节添加音标"""
    file_path = Path('json_chapters/自然地理.json')
    
    # 读取现有JSON
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # 为每个单词添加音标
    updated_count = 0
    for word_entry in data['words']:
        word = word_entry['word']
        # 处理组合词（如 jeopardise/jeopardize）
        if '/' in word:
            parts = word.split('/')
            if parts[0] in phonetics_data:
                word_entry['phonetic'] = phonetics_data[parts[0]]
                updated_count += 1
        elif word in phonetics_data:
            word_entry['phonetic'] = phonetics_data[word]
            updated_count += 1
        else:
            # 对于没有音标数据的单词，暂时留空
            print(f"Missing phonetic for: {word}")
    
    # 保存更新后的JSON
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"成功为 {updated_count} 个单词添加了音标")
    print(f"文件已更新: {file_path}")

if __name__ == "__main__":
    add_phonetics_to_json()