#!/usr/bin/env python3
import json
from pathlib import Path

# 记忆技巧数据
tips_data = {
    "atmosphere": "联想'atmo'像'atom'(原子)+'sphere'(球体)，原子组成的球体包围地球就是大气层",
    "hydrosphere": "hydro(水)+sphere(球体)，地球上所有水形成的圈层",
    "lithosphere": "litho(石头)+sphere(球体)，石头组成的圈层就是岩石圈",
    "oxygen": "O2，想象两个O像眼睛，需要氧气才能睁开眼睛",
    "oxide": "oxygen(氧)+ide(化合物后缀)，氧的化合物",
    "carbon dioxide": "二氧化碳CO2，car(车)排放carbon dioxide",
    "hydrogen": "H元素，最轻的气体，像氢气球会飞向sky",
    "core": "苹果核(apple core)，地球也有核心",
    "crust": "面包皮(bread crust)，地球表面的硬壳",
    "mantle": "man穿mantle(斗篷)，地幔像斗篷包裹地核",
    "longitude": "long(长)+itude，经线从北极到南极很长",
    "latitude": "lat(横向)+itude，纬线横向环绕地球",
    "horizon": "horizontal(水平的)去掉tal，地平线是水平的",
    "altitude": "alt(高)+itude，高度、海拔",
    "disaster": "dis(不)+aster(星星)，星星不吉利带来灾难",
    "mishap": "mis(错误)+hap(发生)，错误发生就是小灾难",
    "catastrophic": "cat(猫)+astrophe，像猫打翻东西造成的灾难",
    "calamity": "calm(平静)反义，不平静就是灾难",
    "endanger": "en(使)+danger(危险)，使陷入危险",
    "jeopardise": "像jeopardy(危险游戏节目)，使处于危险中",
    "destructive": "de(去掉)+struct(结构)+ive，破坏结构的",
    "El Nino": "西班牙语'小男孩'，圣诞节前后出现的暖流现象",
    "greenhouse": "green(绿色)+house(房子)，种植物的温室",
    "phenomenon": "pheno(显现)+menon，显现出来的现象",
    "pebble": "小p像小石头，ebble听起来像bubble(泡泡)一样圆",
    "magnet": "mag(魔法)+net(网)，像魔法网一样吸引铁",
    "ore": "or(或者)+e，矿石或可提炼金属",
    "mineral": "mine(矿)+ral，从矿中提取的物质",
    "marble": "mar(玛丽)+ble，玛丽喜欢的白色石头",
    "quartz": "quarter(四分之一)，石英晶体常呈六面体",
    "granite": "gran(颗粒)+ite，颗粒状的花岗岩",
    "gust": "g+ust(我们)，一阵风吹向我们",
    "breeze": "breeze听起来像'轻松'，微风让人轻松",
    "monsoon": "moon+soon，月亮来了雨季就到了",
    "gale": "gale像'盖儿'，大风要盖住帽子",
    "hurricane": "hurry(赶快)+cane(手杖)，飓风来了赶快拿手杖逃",
    "tornado": "torn(撕裂)+ado，龙卷风撕裂一切",
    "typhoon": "太(ty)+风(phoon)，太平洋的风",
    "volcano": "vol(飞)+cano(罐子)，岩浆像从罐子里飞出",
    "erupt": "e(出)+rupt(破裂)，破裂喷出",
    "magma": "mag(大)+ma(妈)，地球妈妈体内的岩浆",
    "thermodynamic": "thermo(热)+dynamic(动力)，热力学的",
    "smog": "smoke(烟)+fog(雾)=烟雾",
    "fume": "fume像'发霉'，有害气体像发霉的味道",
    "mist": "mist像'迷失'，薄雾中容易迷失",
    "tsunami": "日语'津波'，港口的大波浪",
    "drought": "d+rough(粗糙)+t，干旱使土地粗糙",
    "flooding": "flood(洪水)+ing，洪水泛滥",
    "torrent": "tor(撕裂)+rent(租)，激流撕裂河岸",
    "earthquake": "earth(地)+quake(震动)，大地震动",
    "seismic": "seism(地震)+ic，地震相关的",
    "avalanche": "ava(向下)+lanche(发射)，雪向下发射",
    "terrain": "terr(土地)+ain，地形地貌",
    "landscape": "land(土地)+scape(景色)，土地的景色",
    "continent": "con(共同)+tin(罐子)+ent，像罐子一样的大陆板块",
    "cave": "cave像'凹'，山洞是凹进去的",
    "cliff": "cli(爬)+ff，需要攀爬的悬崖",
    "glacier": "glac(玻璃)+ier，像玻璃一样的冰川",
    "swamp": "s+wamp(湿)，湿地沼泽",
    "delta": "希腊字母Δ，河口三角洲的形状",
    "plain": "plain(平的)，平原是平坦的",
    "plateau": "plate(盘子)+au，像盘子一样平的高原",
    "oasis": "o(圆)+asis，沙漠中的圆形绿洲",
    "globe": "global(全球的)，地球是个球体",
    "hemisphere": "hemi(半)+sphere(球)，半球",
    "equator": "equal(相等)+tor，南北半球相等的分界线",
    "arctic": "arc(弧)+tic，北极圈是地球顶端的弧",
    "Antarctic": "anti(相反)+arctic，与北极相反的南极",
    "pole": "pole像'破'了，地球两极破开的点",
    "polar": "pole+ar，极地的，北极熊polar bear",
    "axis": "axis像'爱克斯'，X轴，地球自转轴",
    "deteriorate": "de(向下)+terior(更坏)+ate，越来越坏",
    "aggravate": "agg(增加)+grave(严重)，使更严重",
    "degrade": "de(向下)+grade(等级)，降级、恶化",
    "upgrade": "up(向上)+grade(等级)，升级、改善",
    "erode": "e(出)+rode(ride过去式)，被水流冲走",
    "Mediterranean": "medi(中间)+terra(土地)+nean，欧非之间的海",
    "Atlantic": "Atlas(阿特拉斯)+ic，神话巨人托起的大洋",
    "pacific": "peace(和平)+ic，太平洋，和平的海洋",
    "ocean": "o+cean像'哦,深'，海洋很深",
    "marine": "mar(海)+ine，海洋相关的",
    "navigation": "navi(船)+gation，船的导航",
    "gulf": "gulf像'gap'，海湾是陆地的缺口",
    "beach": "beach像'必去'，海滩是度假必去之地",
    "coast": "coast像'靠岸'，海岸线",
    "shore": "shore像'sure'，确定到达岸边",
    "tide": "tide像'太的'，潮汐是太阳月亮造成的",
    "current": "current(当前的)，水流是当前流动的",
    "brook": "brook像book，小溪像书页一样薄",
    "stream": "stream像'溪流'的音，小河流动",
    "source": "source(来源)，河流的源头",
    "shallow": "shall(应该)+ow，浅水应该能站立",
    "superficial": "super(超级)+ficial(表面)，超级表面的",
    "flat": "flat像'服啦'，平坦地服在地上",
    "smooth": "smooth像'是木头'，木头打磨光滑",
    "rough": "rough像'乳沟'，粗糙不平",
    "sandy": "sand+y，沙子多的",
    "stony": "stone+y，石头多的",
    "vertical": "verti(转)+cal，垂直90度转向",
    "steep": "steep像'死地扑'，陡峭易摔倒",
    "parallel": "para(旁边)+llel(线)，平行线",
    "narrow": "narrow像'那肉'，狭窄得只能过那一块肉",
    "Oceania": "ocean(海洋)+ia，大洋洲多岛屿",
    "mainland": "main(主要)+land(陆地)，大陆主体",
    "peninsula": "pen(笔)+insula(岛)，像笔伸入海中的半岛",
    "climate": "clim(爬)+ate，随纬度爬升变化的气候",
    "weather": "weather像'为了'，为了适应天气",
    "meteorology": "meteor(流星)+ology(学科)，研究大气现象",
    "mild": "mild像'妙的'，温和美妙的天气",
    "heating": "heat(热)+ing，供暖系统",
    "moderate": "mode(模式)+rate(速率)，适中的模式",
    "warm": "warm像'我暖'，温暖的感觉",
    "thermal": "therm(热)+al，热量相关的",
    "tropics": "tropic(回归线)+s，热带地区",
    "arid": "a+rid(摆脱)，摆脱水分就干旱",
    "moist": "moist像'冒湿的'，潮湿的",
    "damp": "damp像'大棚'，大棚里潮湿",
    "humid": "hum(嗡嗡)+id，潮湿闷热蚊子嗡嗡叫",
    "snowy": "snow+y，多雪的",
    "frost": "frost像'否认热'，霜冻否认热量",
    "hail": "hail像'嗨哦'，冰雹打得人喊嗨哦",
    "thaw": "thaw像'它化'，冰雪融化",
    "chill": "chill像'吃冷'，吃冷东西感到寒冷",
    "freeze": "freeze像'冻住了'的音",
    "frigid": "frig(冰箱refrigerator)+id，像冰箱里一样冷",
    "tremble": "tremble像'船舶'，冷得像船舶摇晃",
    "shiver": "shiver像'谁我'，冷得发抖问谁是我",
    "thunder": "thunder像'桑德'，雷神之锤的声音",
    "lightning": "light(光)+ning，闪电的光",
    "stormy": "storm+y，暴风雨的",
    "downpour": "down(向下)+pour(倾倒)，倾盆大雨",
    "rainfall": "rain(雨)+fall(落下)，降雨量",
    "sprinkle": "spring(春天)+kle，春天洒下小雨",
    "rainbow": "rain(雨)+bow(弓)，雨后的彩虹弓",
    "shower": "shower像'秀儿'，阵雨像秀儿般短暂",
    "Celsius": "C氏温度，中国常用摄氏度",
    "temperature": "temper(脾气)+ature，温度影响脾气",
    "forecast": "fore(前)+cast(投射)，预先投射未来",
    "peak": "peak像'批克'，山峰顶点",
    "mount": "mount像'山'的音，登山",
    "mountain": "mount+ain，高山",
    "range": "range(范围)，山脉的范围",
    "ridge": "ridge像'ridge'，山脊像屋脊",
    "slope": "slope像'死落扑'，斜坡容易滑落",
    "valley": "valley像'外力'，外力侵蚀形成山谷",
    "hillside": "hill(小山)+side(边)，山坡",
    "overlook": "over(在上)+look(看)，俯瞰",
    "southern": "south+ern，南方的",
    "oriental": "orient(东方)+al，东方的",
    "inevitable": "in(不)+evit(避免)+able，不可避免的",
    "irreversible": "ir(不)+reverse(逆转)+ible，不可逆转的",
    "irregularly": "ir(不)+regular(规则)+ly，不规则地",
    "inappropriate": "in(不)+appropriate(合适)，不合适的",
    "abnormal": "ab(离开)+normal(正常)，不正常的",
    "sediment": "sed(坐)+iment，沉淀物坐在底部",
    "silt": "silt像'湿泥土'，淤泥",
    "muddy": "mud(泥)+dy，泥泞的",
    "clay": "clay像'克雷'，陶土可塑形",
    "dirt": "dirt像'地土'，泥土污垢",
    "rural": "rural像'乳肉'，农村产乳肉",
    "suburb": "sub(下)+urb(城市)，城市下属郊区",
    "outskirts": "out(外)+skirts(裙边)，城市外围边缘",
    "remote": "re(再)+mote(移动)，移得很远的",
    "desolate": "de(去)+sol(太阳)+ate，没有阳光般荒凉",
    "distant": "dis(分开)+tant，分开很远的距离",
    "adjacent": "ad(向)+jacent(躺)，紧挨着躺着的",
    "toxic": "tox(毒)+ic，有毒的",
    "pollutant": "pollute(污染)+ant，污染物",
    "contaminate": "con(共同)+tamin(触碰)+ate，被污染物触碰",
    "geology": "geo(地)+ology(学科)，地质学",
    "border": "border像'包的'，边界包围的",
    "margin": "marg(标记)+in，页边的标记",
    "fringe": "fringe像'飞润至'，边缘地带",
    "plate": "plate(盘子)，地球板块像盘子",
    "debris": "de(去)+bris，破碎后留下的残骸",
    "crack": "crack像开裂的声音，裂缝",
    "gap": "gap像'隔'，缺口隔开两边",
    "splendid": "splend(发光)+id，光辉壮观的",
    "grand": "grand像'光荣的'，宏伟的",
    "magnificent": "magni(大)+fic(做)+ent，做得很大很壮观",
    "dramatic": "drama(戏剧)+tic，戏剧性的",
    "wilderness": "wild(野生)+erness，荒野之地",
    "desert": "desert像'得舍弃'，沙漠得舍弃水分",
    "deforest": "de(去)+forest(森林)，毁林",
    "barren": "barren像'白跑'，贫瘠土地白跑一趟",
    "fertile": "fert(带来)+ile，带来丰收的肥沃土地",
    "fertilise": "fertile+ise，使肥沃，施肥",
    "solar": "sol(太阳)+ar，太阳的",
    "lunar": "lun(月亮)+ar，月亮的",
    "calendar": "cal(计算)+endar，计算日期的日历",
    "sunrise": "sun(太阳)+rise(升起)，日出",
    "eclipse": "e(出)+clipse(剪)，日月被剪掉一块",
    "dusk": "dusk像'大色开'，天色大开始变暗",
    "heaven": "heaven像'和文'，天堂和文明",
    "paradise": "para(旁边)+dise(dice骰子)，天堂般的运气",
    "sunshine": "sun(太阳)+shine(照耀)，阳光",
    "shade": "shade像'晒的'反义，不被晒的阴凉处",
    "shadow": "shade+ow，阴影",
    "vapour": "vap(蒸发)+our，我们的蒸汽",
    "evaporate": "e(出)+vapor(蒸汽)+ate，变成蒸汽",
    "circulate": "circul(圆圈)+ate，循环流通",
    "precipitate": "pre(前)+cipit(头)+ate，头朝下沉淀",
    "reservoir": "reserve(储备)+oir，储备水的水库",
    "fountain": "fount(泉源)+ain，喷泉",
    "spring": "spring(弹簧、春天)，泉水像弹簧涌出",
    "dew": "dew像'丢'，露水早晨会丢(蒸发)",
    "pour": "pour像'泼'，倾倒",
    "drain": "drain像'拽'，排水拽走",
    "drip": "drip像'滴'的音，滴水",
    "drown": "drown像'撞'水里，淹死",
    "blow": "blow像'不漏'，吹气不漏",
    "puff": "puff像喷气的声音，喘息",
    "gush": "gush像'嘎许'，水涌出的声音",
    "dense": "dense像'顶死'，密集得顶死了",
    "intensity": "in(内)+tens(紧张)+ity，内在的强度",
    "intensive": "intense(强烈)+ive，密集的",
    "emerge": "e(出)+merge(沉没)，从沉没中浮现",
    "flash": "flash像'飞来许'，闪电飞来",
    "float": "float像'浮漏的'，漂浮",
    "surrounding": "surround(围绕)+ing，周围的",
    "condition": "con(共同)+dition，共同的条件状况",
    "artificial": "art(技术)+ficial，人工技术制造的",
    "synthetic": "syn(共同)+thet(放)+ic，放在一起合成的",
    "petrol": "petr(石)+ol(油)，石油提炼的汽油",
    "gas": "gas像'嘎斯'，气体",
    "gasoline": "gas+oline(油)，汽油",
    "petroleum": "petr(石)+oleum(油)，石油"
}

def add_tips_to_json():
    """为自然地理章节添加记忆技巧"""
    file_path = Path('json_chapters/自然地理.json')
    
    # 读取现有JSON
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # 为每个单词添加tips
    updated_count = 0
    for word_entry in data['words']:
        word = word_entry['word']
        if word in tips_data:
            word_entry['tips'] = tips_data[word]
            updated_count += 1
        else:
            # 对于没有特定tips的单词，生成通用提示
            word_entry['tips'] = f"将'{word}'与相关场景联想，结合例句反复练习"
    
    # 保存更新后的JSON
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"成功为 {updated_count} 个单词添加了记忆技巧")
    print(f"文件已更新: {file_path}")

if __name__ == "__main__":
    add_tips_to_json()